### ISSUE TITLE
Little issue in the readme

### ISSUE THREAD

**Issue by imclint21** [Stebalien/snowflake#11]
its extern crate snowflake; not create ^^

and please make a little snippet to generate a snowflake :)

**Comment by Stebalien** [comment]
Could you submit a PR to fix that?

**Comment by imclint21** [comment]
Yeah, just said me how to use your lib haha, i tried an i give a uid-0-0 something like this

@Stebalien, just give me a little snippet and I make a PR with the fix, and the getting started example

**Comment by Stebalien** [comment]
There's not much too it:

```rust
use snowflake::ProcessUniqueId;

let id1 = ProcessUniqueId::new();
let id2 = ProcessUniqueId::new();
...
```

Then you can use these IDs anywhere you need a process-wide unique ID.

**Comment by imclint21** [comment]
Ha yes it's what I do normally, but why I have an empty ID? 🤔

**Comment by Stebalien** [comment]
That's just the first ID.

**Comment by imclint21** [comment]
Ha, I'm an idiot
